version: '2'
services:
  zk-1:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-1
    ports:
      - "10000:10000"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 10000
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:18881:18882;zk-2:28881:28882;zk-3:38881:38882
    networks:
      - proxy

  zk-2:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-2
    ports:
      - "20000:20000"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 20000
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:18881:18882;zk-2:28881:28882;zk-3:38881:38882
    networks:
      - proxy

  zk-3:
    image: confluentinc/cp-zookeeper:latest
    hostname: zk-3
    ports:
      - "30000:30000"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 30000
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zk-1:18881:18882;zk-2:28881:28882;zk-3:38881:38882
    networks:
      - proxy

  kfk-1:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-1
    ports:
      - "20001:20001"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk-1:10000,zk-2:10000,zk-3:10000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-1:20001
    networks:
      - proxy
 
  kfk-2:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-2
    ports:
      - "30001:30001"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk-1:10000,zk-2:10000,zk-3:10000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-2:30001
    networks:
      - proxy
 
  kfk-3:
    image: confluentinc/cp-kafka:latest
    hostname: kfk-3
    ports:
      - "40001:40001"
    depends_on:
      - zk-1
      - zk-2
      - zk-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zk-1:10000,zk-2:10000,zk-3:10000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfk-3:40001
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
